name: Production CI & CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: ci-prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  deploy:
    name: cd-prod
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_PASSPHRASE }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/dlab/apps/gameown-website
            git pull origin main
            npm ci
            npm run build --if-present
            echo "" > .env
            echo "PORT=${{ secrets.APP_PORT }}" >> .env
            echo "REACT_APP_ENV=${{ secrets.APP_ENV }}"" >> .env
            pm2 stop gameown-website
            pm2 delete gameown-website
            pm2 --name "gameown-core" serve --spa build secrets.APP_PORT